-- PROGRAM 18: LIKE Operator Using Cursor FOR Loop


SET SERVEROUTPUT ON;

CREATE TABLE CUSTOMER18
(
    CID NUMBER PRIMARY KEY,
    CName VARCHAR2(30),
    City VARCHAR2(30),
    Phone VARCHAR2(15)
);

INSERT INTO CUSTOMER18 VALUES (1, 'RAHUL', 'AHMEDABAD', '9876543210');
INSERT INTO CUSTOMER18 VALUES (2, 'AMIT', 'GANDHIDHAM', '9876543211');
INSERT INTO CUSTOMER18 VALUES (3, 'RAJ', 'RAJKOT', '9876543212');
INSERT INTO CUSTOMER18 VALUES (4, 'NEHA', 'SURAT', '9876543213');

COMMIT;

BEGIN
    FOR C IN
    (
        SELECT CID, CName, City
        FROM CUSTOMER18
        WHERE CName LIKE 'RA%'
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            C.CID || ' ' || C.CName || ' ' || C.City
        );
    END LOOP;
END;
/
